"""Shared constants — regimes, actions, defaults."""

REGIME_BULL = "bull"
REGIME_BEAR = "bear"
REGIME_SIDEWAYS = "sideways"

REF_SYMBOL = "BTC/USDT:USDT"
DEFAULT_TIMEFRAME = "15m"
OHLCV_LIMIT = 120

ACTION_MONITOR = "MONITOR"
ACTION_REDUCE = "REDUCE_ALLOCATION"
ACTION_INCREASE = "INCREASE_ALLOCATION"

STRATEGY_TREND = "trend"
STRATEGY_MEAN_REVERSION = "mean_reversion"
STRATEGY_BREAKOUT = "breakout"
STRATEGY_MOMENTUM = "momentum"
STRATEGY_FUNDING = "funding_arb"

MIN_SCANNER_SCORE = 0.35
MIN_TRADE_NOTIONAL_USDT = 10.0
