"""Dual strategy configuration for Quant Singularity."""

from config.settings import _env_bool, _env_float, _env_int

TOTAL_CAPITAL = _env_float("QS_TOTAL_CAPITAL", 1000)

PASSIVE_CAPITAL = _env_float("QS_PASSIVE_CAPITAL", 700)
PASSIVE_TIMEFRAMES = ["4h", "1d"]
PASSIVE_MAX_POSITIONS = _env_int("QS_PASSIVE_MAX_POSITIONS", 3)
PASSIVE_MAX_POSITION_SIZE = _env_float("QS_PASSIVE_MAX_POSITION_SIZE", PASSIVE_CAPITAL / 3)
PASSIVE_TAKE_PROFIT = _env_float("QS_PASSIVE_TAKE_PROFIT", 0.10)
PASSIVE_STOP_LOSS = _env_float("QS_PASSIVE_STOP_LOSS", 0.05)
PASSIVE_MIN_HOLD_HOURS = _env_int("QS_PASSIVE_MIN_HOLD_HOURS", 72)
PASSIVE_MAX_HOLD_HOURS = _env_int("QS_PASSIVE_MAX_HOLD_HOURS", 336)
PASSIVE_MAX_DRAWDOWN = _env_float("QS_PASSIVE_MAX_DRAWDOWN", 0.10)
PASSIVE_REGIME_BLACKLIST = []  # ADX filter in PassiveStrategy guards against choppy entries

ACTIVE_CAPITAL = _env_float("QS_ACTIVE_CAPITAL", 300)
ACTIVE_TIMEFRAMES = ["5m", "15m", "1h"]
ACTIVE_MAX_POSITIONS = _env_int("QS_ACTIVE_MAX_POSITIONS", 3)
ACTIVE_MAX_POSITION_SIZE = _env_float("QS_ACTIVE_MAX_POSITION_SIZE", ACTIVE_CAPITAL / 3)
ACTIVE_TAKE_PROFIT = _env_float("QS_ACTIVE_TAKE_PROFIT", 0.015)
ACTIVE_STOP_LOSS = _env_float("QS_ACTIVE_STOP_LOSS", 0.007)
ACTIVE_MAX_DAILY_LOSS = _env_float("QS_ACTIVE_MAX_DAILY_LOSS", ACTIVE_CAPITAL * 0.05)  # 5% of active
ACTIVE_DAILY_TARGET_PCT = _env_float("QS_ACTIVE_DAILY_TARGET_PCT", 0.0286)  # ~2.86% of active ≈ 300 THB/day
ACTIVE_DAILY_LOSS_PCT   = _env_float("QS_ACTIVE_DAILY_LOSS_PCT",   0.05)   # 5% of active = daily loss gate
ACTIVE_TRADING_START = _env_int("QS_ACTIVE_TRADING_START", 0)
ACTIVE_TRADING_END = _env_int("QS_ACTIVE_TRADING_END", 24)

DYNAMIC_ALLOCATION = _env_bool("QS_DYNAMIC_ALLOCATION", True)
ALLOCATION_REBALANCE_CYCLES = _env_int("QS_ALLOCATION_REBALANCE_CYCLES", 240)  # every ~1 hour
ALLOCATION_STEP = _env_float("QS_ALLOCATION_STEP", 0.03)  # 3% per rebalance (was 5%)
ALLOCATION_SCORE_THRESHOLD = _env_float("QS_ALLOCATION_SCORE_THRESHOLD", 0.01)
ALLOCATION_MIN_TRANSFER = _env_float("QS_ALLOCATION_MIN_TRANSFER", max(5.0, TOTAL_CAPITAL * 0.005))
ACTIVE_MIN_CAPITAL_FRACTION = _env_float("QS_ACTIVE_MIN_CAPITAL_FRACTION", 0.20)
ACTIVE_MAX_CAPITAL_FRACTION = _env_float("QS_ACTIVE_MAX_CAPITAL_FRACTION", 0.40)
DUAL_ALLOW_SAME_SYMBOL_STACKING = _env_bool("QS_DUAL_ALLOW_SAME_SYMBOL_STACKING", False)

MAX_PORTFOLIO_DRAWDOWN = _env_float("QS_MAX_PORTFOLIO_DRAWDOWN", 0.15)
KILL_SWITCH_EQUITY = _env_float("QS_KILL_SWITCH_EQUITY", TOTAL_CAPITAL * 0.85)

PASSIVE_LEVERAGE = _env_int("QS_PASSIVE_LEVERAGE", 1)   # long-term: no leverage
ACTIVE_LEVERAGE  = _env_int("QS_ACTIVE_LEVERAGE",  2)   # intraday: 2x

DUAL_MODE = _env_bool("QS_DUAL_MODE", False)
